version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: [--auth]
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: dev
    restart: always
    volumes:
            - ./initdb:/docker-entrypoint-initdb.d
            - ./data:/data/db
            - ./configdb:/data/configdb
    ports:
      - 27017:27017