version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro 
            - ./logs:/var/log/nginx
            - ./html:/usr/share/nginx/html
    ports:
      - 8100:80