version: '3'
services:
  myredis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    privileged: true
    command: redis-server /etc/redis/redis.conf --appendonly yes
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis.conf
#     networks:
#       - devops-network

# networks:

#   devops-network:
#     driver: bridge